export const ventureCapitals = [
  {
    alt: 'PayPal Ventures',
    icon: '/images/landingpage/investors/paypal_ventures.svg',
  },
  {
    alt: 'Cherubic Ventures',
    icon: '/images/landingpage/investors/cherubic.svg',
  },
  { alt: 'Northzone', icon: '/images/landingpage/investors/northzone.svg' },
  { alt: 'Placeholder', icon: '/images/landingpage/investors/placeholder.svg' },
  {
    alt: 'Lightspeed Ventures',
    icon: '/images/landingpage/investors/lightspeed.svg',
  },
  { alt: 'SV Angel', icon: '/images/landingpage/investors/sv_angel.svg' },
  {
    alt: 'Social Capital',
    icon: '/images/landingpage/investors/social_capital.svg',
  },
  {
    alt: 'Digital Currency Group',
    icon: '/images/landingpage/investors/digital_currency_group.svg',
  },
  { alt: 'CoinFund', icon: '/images/landingpage/investors/coinfund.svg' },
  { alt: 'Volt Capital', icon: '/images/landingpage/investors/volt_capital.svg' },
  { alt: 'Tiger Global', icon: '/images/landingpage/investors/tiger_global.svg' },
  {
    alt: 'Synchrony',
    icon: '/images/landingpage/investors/synchrony.svg',
  },
  {
    alt: 'KX',
    icon: '/images/landingpage/investors/kx.svg',
  },
];

export const angelInvestors = [
  {
    name: 'Wendy Xiao Schadeck',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/wendy-xiao-schadeck.png',
    role: 'Partner, Northzone',
    handle: 'https://twitter.com/wen_xs	',
  },
  {
    name: 'Joel Monegro',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/joel-monegro.png',
    role: 'Partner, Placeholder',
    handle: 'https://twitter.com/jmonegro',
  },
  {
    name: 'Naval Ravikant',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/naval-ravikant.png',
    role: 'Co-founder, AngelList',
    handle: 'https://twitter.com/naval',
  },
  {
    name: 'Balaji Srinivasan',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/balaji-srinivasan.png',
    role: 'Co-founder, Earn.com',
    handle: 'https://twitter.com/balajis',
  },
  {
    name: 'Ryan Hoover',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/ryan-hoover.png',
    role: 'Founder, Product Hunt',
    handle: 'https://twitter.com/rrhoover',
  },
  {
    name: 'Alexis Ohanian',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/alexis-ohanian.png',
    role: 'Co-founder, Reddit',
    handle: 'https://twitter.com/alexisohanian',
  },
  {
    name: 'Soona Amhaz',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/soona-amhaz.png',
    role: 'General Partner, Volt Capital ',
    handle: 'https://twitter.com/soona',
  },
  {
    name: 'Scott Belsky',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/scott-belsky.png',
    role: 'CPO, Adobe',
    handle: 'https://twitter.com/scottbelsky',
  },
  {
    name: 'Jason Warner',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/jason-warner.png',
    role: 'CTO, GitHub',
    handle: 'https://twitter.com/jasoncwarner',
  },
  {
    name: 'Kayvon Beykpour',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/kayvon-beykpour.png',
    role: 'Co-founder, Periscope',
    handle: 'https://twitter.com/kayvz',
  },
  {
    name: 'Roham Gharegozlou',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/roham-gharegozlou.png',
    role: 'CEO, Dapper Labs',
    handle: 'https://twitter.com/rohamg',
  },
  {
    name: 'Varsha Rao',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/varsha-rao.png',
    role: 'CEO, Nurx',
    handle: 'https://twitter.com/varsharao',
  },
  {
    name: 'Sahil Lavingia',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/sahil-lavingia.png',
    role: 'CEO, Gumroad',
    handle: 'https://twitter.com/shl',
  },
  {
    name: 'Jacob Jaber',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/jacob-jaber.png',
    role: 'CEO, Philz Coffee',
    handle: 'https://twitter.com/JacobJaber',
  },
  {
    name: 'Guillermo Rauch',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/guillermo-rauch.png',
    role: 'CEO, Vercel & Next.js',
    handle: 'https://twitter.com/rauchg',
  },
  {
    name: 'Hana Yang',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/hana-yang.png',
    role: 'Co-founder, Allocate',
    handle: 'https://twitter.com/hanayang',
  },
  {
    name: 'Alex MacCaw',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/alex-maccaw.png',
    role: 'Founder, ClearBit',
    handle: 'https://twitter.com/maccaw',
  },
  {
    name: 'Ben Pruess',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/ben-pruess.png',
    role: 'President, Tommy Hilfiger',
    handle: 'https://linkedin.com/in/bpruess',
  },
  {
    name: 'Casey Neistat',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/casey-neistat.png',
    role: 'Filmmaker',
    handle: 'https://twitter.com/Casey',
  },
  {
    name: 'Miyuki Matsumoto',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/miyuki-matsumoto.png',
    role: 'Managing Partner, Aglaé Ventures',
    handle: 'https://www.linkedin.com/in/miyuki-matsumoto-7468162/',
  },
  {
    name: 'Shiva Rajaraman',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/shiva-rajaraman.png',
    role: 'VP of Commerce, Facebook',
    handle: 'https://twitter.com/shivar',
  },
  {
    name: 'Alex Bouaziz',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/alex-bouaziz.png',
    role: 'CEO, Deel',
    handle: 'https://twitter.com/bouazizalex',
  },
  {
    name: 'Natasja Nielsen',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/natasja-nielsen.png',
    role: 'CTO, SecureFrame',
    handle: 'https://twitter.com/chiefnatasja',
  },
  {
    name: 'Ben Porterfield',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/ben-porterfield.png',
    role: 'Founder, Looker',
    handle: 'https://twitter.com/benporterfield',
  },
  {
    name: 'Stella Garber',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/stella-garber.png',
    role: 'Head of Marketing, Atlassian',
    handle: 'https://twitter.com/startupstella',
  },
  {
    name: 'Ben Davenport',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/ben-davenport.png',
    role: 'Partner, Blockchain Capital',
    handle: 'https://twitter.com/bendavenport',
  },
  {
    name: 'Alvin Tse',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/alvin-tse.png',
    role: 'Head of Xiaomi Indonesia',
    handle: 'https://twitter.com/atytse',
  },
  {
    name: 'Jana Messerschmidt',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/jana-messerschmidt.png',
    role: 'Founding Partner, #ANGELS',
    handle: 'https://twitter.com/janamal',
  },
  {
    name: 'Mike Rosengarten',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/mike-rosengarten.png',
    role: 'Founder, Camino',
    handle: 'https://twitter.com/itsmikerose',
  },
  {
    name: 'Hiten Shah',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/hiten-shah.png',
    role: 'Co-founder, Nira',
    handle: 'https://twitter.com/hnshah',
  },
  {
    name: 'Max Altschuler',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/max-altschuler.png',
    role: 'Founder, GTMFund',
    handle: 'https://twitter.com/HackItMax',
  },
  {
    name: 'Valentine Wallace',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/valentine-wallace.png',
    role: 'Bitcoin Core & Lightning, Square Crypto',
    handle: 'https://twitter.com/vallywal',
  },
  {
    name: 'Chris Ye',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/chris-ye.png',
    role: 'CEO, Uken Games',
    handle: 'https://linkedin.com/in/cye',
  },
  {
    name: 'David Booth',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/david-booth.png',
    role: 'CEO, On Deck',
    handle: 'https://twitter.com/david__booth',
  },
  {
    name: 'Shahed Khan',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/shahed-khan.png',
    role: 'Co-founder, Loom',
    handle: 'https://twitter.com/_shahedk',
  },
  {
    name: 'Abbas Zaidi',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/abbas-zaidi.png',
    role: 'VP, Goldman Sachs',
    handle: 'https://www.linkedin.com/in/abbasazaidi/',
  },
  {
    name: 'Jordan Kong',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/jordan-kong.png',
    role: 'Investor, Atomic',
    handle: 'https://twitter.com/ImNotJK',
  },
  {
    name: 'Paul Yacoubian',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/paul-yacoubian.png',
    role: 'CEO, CopyAI',
    handle: 'https://twitter.com/PaulYacoubian',
  },
  {
    name: 'Julien Bouteloup',
    avatar: '/images/landing-page-july-2021/investors-section/angel-investors/julien-bouteloup.png',
    role: 'CEO, Stake Capital',
    handle: 'https://twitter.com/bneiluj',
  },
];
